#define HAVE_MEMORY_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRDUP 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define MAJOR_VERSION 3
#define MICRO_VERSION 9
#define MINOR_VERSION 0
#define PACKAGE "libqrencode"
#define VERSION "3.9.0"
#define inline _inline
